P1Dashboard/Controllers/LoggingController.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace P1Dashboard.Controllers
{
    public class LoggingController : BaseController
    {
        [SuppressMessage("ReSharper", "SuggestBaseTypeForParameter")]
        public LoggingController(ILogger<LoggingController> logger) : base(logger)
        {
        }

        [HttpGet]
        [ActionName("Index")]
        public IActionResult GetIndex()
        {
            return View();
        }
    }
}

P1Dashboard/Controllers/StatisticsController.cs
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using P1Dashboard.Data;
using P1Dashboard.Extensions;
using P1Dashboard.Models;
using P1Dashboard.P1.Handlers;

namespace P1Dashboard.Controllers
{
    public class StatisticsController : BaseController
    {
        [SuppressMessage("ReSharper", "SuggestBaseTypeForParameter")]
        public StatisticsController(ILogger<StatisticsController> logger, Settings settings, DatabaseContext database, CurrentInfoHandler currentInfo) : base(logger)
        {
            _settings = settings;
            _database = database;
            _currentInfo = currentInfo;
        }

        private readonly Settings _settings;
        private readonly DatabaseContext _database;
        private readonly CurrentInfoHandler _currentInfo;

        [HttpGet]
        [ActionName("Index")]
        public IActionResult GetIndex()
        {
            return View();
        }

        [HttpGet]
        [ActionName("Charts")]
        public async Task<IActionResult> GetCharts()
        {
            var current = _currentInfo.Info;
            const int limit = 13; // Effectively 12 entries because the last one is just used for calculations.

            var model = new ChartsModel
            {
                TimeStamp = current.Timestamp,
                DayMeasurements = await _database.OrderedMeasurements.ByPeriod(MeasurementPeriod.Day).LimitAsync(limit),
                WeekMeasurements = await _database.OrderedMeasurements.ByPeriod(MeasurementPeriod.Week).LimitAsync(limit),
                MonthMeasurements = await _database.OrderedMeasurements.ByPeriod(MeasurementPeriod.Month).LimitAsync(limit),
                YearMeasurements = await _database.OrderedMeasurements.ByPeriod(MeasurementPeriod.Year).LimitAsync(limit)
            };

            model.DayMeasurements.Add(MeasurementModel.FromP1Info(current, MeasurementPeriod.Day));
            model.WeekMeasurements.Add(MeasurementModel.FromP1Info(current, MeasurementPeriod.Week));
            model.MonthMeasurements.Add(MeasurementModel.FromP1Info(current, MeasurementPeriod.Month));
            model.YearMeasurements.Add(MeasurementModel.FromP1Info(current, MeasurementPeriod.Year));

            return View(model);
        }
    }
}

P1Dashboard/Views/Shared/_Layout.cshtml
@inject Settings Settings
@{
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Dashboard - @ViewBag.Title</title>

    <link rel="icon" type="image/png" href="~/Favicon.png" asp-append-version="true">

    <environment include="Development">
        <script src="~/Out/Scripts/Scripts.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="~/Out/Styles/Styles.css" asp-append-version="true">
    </environment>
    <environment exclude="Development">
        <script src="~/Out/Scripts/Scripts.min.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="~/Out/Styles/Styles.min.css" asp-append-version="true">
    </environment>
</head>

<body>
@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">P1 Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Statistics</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="Statistics" asp-action="Index">Home</a>
                        <a class="dropdown-item" asp-controller="Statistics" asp-action="Charts">Charts</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Logging" asp-action="Index">Logging</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
}

@RenderBody()
</body>
</html>